language: python
python:
  - "3.8"
install:
  - pip3 install -r requirements.txt
services:
  - postgresql
script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - coverage run --source='.' manage.py test
  - coverage xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT