language: python

python:
  - "3.8"

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
install:
  - pip3 install -r requirements.txt

services:
  - postgresql

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - coverage run --source='.' manage.py test
  - coverage xml

after_script:
  - ./cc-test-reporter after-build