version: '3'

services:
  database:
    image: postgres:13
    container_name: database    
    environment:
      POSTGRES_PASSWORD: "Museu@2020"
    ports:
      - "5432:5432"
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "diego.morais@usp.br"
      PGADMIN_DEFAULT_PASSWORD: "Museu@2020"
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - database-network

  backend:
    build: .
    container_name: backend
    volumes:
      - .:/code
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"      
    ports:
      - "8000:8000"
    networks:
      - database-network      

networks: 
  database-network:
    driver: bridge