# Generated by Django 2.2.12 on 2020-10-13 01:16

from django.db import migrations, models
import django.db.models.deletion
import museu.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField()),
                ('file', models.FileField(storage=museu.storage.LocalStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('localizacao', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='museu.User')),
            ],
        ),
    ]
