# Generated by Django 3.1.2 on 2020-10-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='media',
        ),
    ]
