# Generated by Django 3.1.2 on 2020-12-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User', to='museu.user'),
        ),
    ]
