# Generated by Django 3.1.2 on 2020-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0002_remove_historia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='media',
            field=models.FileField(default=b'video', upload_to=''),
        ),
    ]
