# Generated by Django 3.1.2 on 2020-11-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0003_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
