# Generated by Django 3.1.2 on 2020-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0003_historia_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='media',
        ),
    ]
