# Generated by Django 3.1.2 on 2020-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0004_remove_historia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='media_url',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='historia',
            name='title',
            field=models.CharField(default='Um lindo título', max_length=140),
        ),
    ]
