# Generated by Django 3.1.2 on 2020-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0005_auto_20201111_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='historia',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='historia',
            name='tags',
            field=models.ManyToManyField(to='museu.Tag'),
        ),
    ]
