# Generated by Django 3.1.2 on 2020-11-11 23:24

from django.db import migrations, models
import museu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0005_auto_20201111_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='historia',
            name='type',
            field=models.CharField(default='text', max_length=5, validators=[museu.validators.validate_historia_type]),
        ),
    ]
